apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: frontend
spec:
  ports:
  - name: front-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: front
  type: LoadBalancer
