apiVersion: v1
kind: Service
metadata:
  labels:
    app: back
  name: backend
spec:
  ports:
  - name: back-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: back
  type: ClusterIP
